#+title: Thursday, 30 October 2025
* Morning checklist
** DONE Tinnitus check
CLOSED: [2025-10-30 Thu 07:50]
Probably a 2.  It seems like it's quieter the last few days.  Could be work?
** DONE Copy calendar for today here
CLOSED: [2025-10-30 Thu 07:50]
** DONE Read calendar for tomorrow, next week - any action items move here as TODO
CLOSED: [2025-10-30 Thu 07:50]


* Journal
Well tuesday was my last day at PSL.  Pretty wild - end of an era.  Now it's on to bigger and better things with Stefan!

Life at home has been simpler and easier.  Less fighting and nonsense the last couple of days.  Katie seemed calmed down after her counseling session on tuesday but I don't know if that's actually related or just a coincidence.

Today I'm finding out if this first foray into hydrea has actually lowered my platelet count sufficiently for us to travel.  It's a pretty scary check, all things considered.  If my count has come down below 1000, off we go to thailand.  If it hasn't... well, we do something else I reckon.  Maybe Katie goes and I go hunting, or we go on a road trip to oregon or idaho or something.

I'm starting to have good ideas for super.  I'm going to start with a cool persona thing.

* Plan for today


* Notes from today
